apiVersion: v1
kind: Pod
metadata:
  name: metrico
  namespace: hub-system
spec:
  serviceAccountName: metrico-serviceaccount
  containers:
  - name: metrico
    image: xerac/metrico:bullseye
    env:
    - name: METRICO_RUN_ID
      value: ""
    - name: METRICO_S3_URL
      value: ""
    - name: METRICO_S3_ACCESS_KEY
      value: ""
    - name: METRICO_S3_SECRET_KEY
      value: ""
    - name: METRICO_NAMESPACE
      value: ""
    - name: METRICO_CONFIGMAP
      value: ""
    - name: METRICO_CONFIGMAP_KEY
      value: ""
