apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: metrico-resources-rolebinding
    namespace: hub-system
subjects:
    - kind: ServiceAccount
      name: metrico-serviceaccount
      namespace: hub-system
roleRef:
    kind: Role
    name: metrico-resources-role
    apiGroup: rbac.authorization.k8s.io
